global using Microsoft.VisualStudio.TestTools.UnitTesting;
global using UniUnboxdAPI.Data;
global using UniUnboxdAPI.Models;
global using UniUnboxdAPI.Models.DataTransferObjects;
global using UniUnboxdAPI.Repositories;
global using UniUnboxdAPI.Services;
global using UniUnboxdAPI.Utilities;
global using UniUnboxdAPITests.TestUtilities;
global using Microsoft.EntityFrameworkCore;